apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-custom
  template:
    metadata:
      labels:
        app: mysql-custom
    spec:
      containers:
      - name: mysql-custom
        image: ardovino/mysql-custom:1.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "meubanco"
