apiVersion: v1
kind: ConfigMap
metadata:
  name: service-cliente-config
  namespace: microservices-assessment
data:
  SPRING_R2DBC_URL: r2dbc:postgresql://postgres-cliente:5432/clientedb
  SPRING_R2DBC_USERNAME: postgres
  SPRING_R2DBC_PASSWORD: postgres
  SERVICE_API_URL: http://service-api:8081
