apiVersion: v1
kind: Service
metadata:
  name: service-cliente
  namespace: microservices-assessment
spec:
  type: ClusterIP
  selector:
    app: service-cliente
  ports:
    - port: 8082
      targetPort: 8082
