apiVersion: v1
kind: ConfigMap
metadata:
  name: service-api-config
  namespace: microservices-assessment
data:
  SPRING_R2DBC_URL: r2dbc:postgresql://postgres-api:5432/produtosdb
  SPRING_R2DBC_USERNAME: postgres
  SPRING_R2DBC_PASSWORD: postgres
  SPRING_PROFILES_ACTIVE: docker
