apiVersion: v1
kind: ConfigMap
metadata:
  name: service-api-config
  namespace: microservices-assessment
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-api:5432/produtosdb
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
