apiVersion: v1
kind: Service
metadata:
  name: service-api
  namespace: microservices-assessment
spec:
  type: ClusterIP
  selector:
    app: service-api
  ports:
    - name: http
      port: 8081
      targetPort: 8081
