apiVersion: v1
kind: Service
metadata:
  name: service-consumer
  namespace: microservices-assessment
spec:
  type: NodePort
  selector:
    app: service-consumer
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
