apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-api
  template:
    metadata:
      labels:
        app: springboot-api
    spec:
      containers:
        - name: springboot-api
          image: ardovino/springboot-api:1.0
          ports:
            - containerPort: 8080
